### PR TITLE
Add permissions for /apps

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by nono** [comment]
> Does it breaks the front dev environment?

Yes, the cozy-bar has no own token for the moment. So, each app needs to have a permission to list the installed apps and get their icon.

**Comment by nono** [comment]
- https://github.com/cozy/cozy-photos-v3/pull/18
- https://github.com/cozy/cozy-files-v3/pull/144
- https://github.com/cozy/cozy-settings/pull/25

**Comment by jinroh** [comment]
Also do not forget the `.travis.yml` of `cozy-client-js` which install an application.

**Comment by nono** [comment]
https://github.com/cozy/cozy-client-js/pull/101

**Pull request merged**
