### PR TITLE
Handle errors in case of issue during the account encryption

### PR DESCRIPTION
**Pull request by Peltoche**

### CODE REVIEW

**Comment by nono** [comment]
The integration tests are failing when creating an account, with a 500 error. Can you look at it?

**Comment by Peltoche** [comment]
> The integration tests are failing when creating an account, with a 500 error. Can you look at it?

I try but I don't find any info inside the logs and I try to replicate the error in local but the script still failing at some random place, I need to debug it first...

I will create an issue in order to discuss this subject without polluting this PR

**Comment by Peltoche** [comment]
Can't find a way to debug this issue... @nono  a little help would be really nice :pleading_face:

**Comment by nono** [comment]
Sorry, I have other priorities for the moment

**Pull request closed without merging**
