### PR TITLE
Allow to show icons for apps with a public route

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by enguerran** [comment]
Can you explain how to declare a public route?

In my application, I added a public route in `manifest.webapp`:

```json
  "routes": {
    "/": {
      "folder": "/",
      "index": "index.html",
      "public": false
    },
    "/public": {
      "folder": "/public",
      "index": "index.html",
      "public": true
    }
  },
```

And within the web application, I request the image with `` when `IconPath` is replaced by the stack to be `http://photos.cozy.tools:8080/app-icon.svg` as described below in a screenshot.

screenshot at 16-35-20

**Comment by enguerran** [comment]
[(1) [PHO-27 Partage d'un album par lien] Création d'une page publique simple](https://trello.com/c/gwhjazOi/279-1-pho-27-partage-d-un-album-par-lien-creation-d-une-page-publique-simple)

**Comment by nono** [comment]
Well, it looks correct to me. Can you try to refresh the page and make a curl request for the icon?

**Comment by enguerran** [comment]
I checked it twice, it returns the same result: `HTTP/1.1 401 Unauthorized`.
What did I do wrong?

**Comment by nono** [comment]
It is easier to move the icon in the public directory (and update the manifest)

**Pull request closed without merging**
