### PR TITLE
Disable CSP from config file

### PR DESCRIPTION
**Pull request by sebn**

### CODE REVIEW

**Comment by jinroh** [comment]
I wonder with this PR if it does not break the precedence of the CLI flag `--disable-csp` over the configuration. In the case where `disable_csp: true` and --disable-csp is set on CLI.

**Comment by jinroh** [comment]
Using `viper.BindPFlag` may work: https://github.com/cozy/cozy-stack/blob/master/cmd/serve.go#L199

**Comment by sebn** [comment]
Thanks for the hint @jinroh, I'll give it a try as soon as possible and make sure it works in every case.

**Comment by nono** [comment]
@sebn can we close this PR and let you open a new one when you will have fixed it?

**Comment by sebn** [comment]
@nono No problem! Sorry for the delay.

**Pull request closed without merging**
