### PR TITLE
Configuration enhancement

### PR DESCRIPTION
**Pull request by tomsquest**
Solves #21  "Configuration enhancement", see there for details

### CODE REVIEW

**Comment by nono** [comment]
Thanks for the PR.

@aenario @jinroh can you look at this PR, and merge it if good for you please?

**Comment by jinroh** [comment]
Great work, thanks @tomsquest !

I know this is not from your modifications, but I would also remove the error printing from the `Execute` error handler in `main.go`. Errors are [printed twice](https://github.com/spf13/cobra/blob/d671d98363b02cd8127087b4675ae77396db5843/command.go#L700-L702):

```go
func main() {
	if err := cmd.RootCmd.Execute(); err != nil {
		fmt.Println(err) // <- redundant (and print in stdout...)
		os.Exit(-1)
	}
}
```

Also the exit code should probably be 1 instead of -1 (255)...

If you're OK with this little change, I'll happily merge your PR.

**Comment by tomsquest** [comment]
@jinroh done + some more (see logs)

**Comment by jinroh** [comment]
Merged. Thanks @tomsquest.

**Pull request merged**
