### PR TITLE
Update Cozy-bar to 3.0.0-beta7

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by nono** [comment]
I've taken your first commit, and updated cozy-client-js too before packing assets. Thanks!

**Comment by m4dz** [comment]
> I've taken your first commit

About it: do you prefer we only commit assets refs and let you pack the stack yourself?

**Comment by nono** [comment]
You can do both. In general, I will merge the PR. It's just this time I also wanted to update cozy-client-js at the same time.

**Comment by m4dz** [comment]
@nono is there a new version of the sack w/ those assets?

**Pull request closed without merging**
