### PR TITLE
Fix the gocritic `elseIf` suggestions

### PR DESCRIPTION
**Pull request by Peltoche**
Those fix have be done following the suggestions from the gocritic linter

### CODE REVIEW

**Comment by nono** [comment]
Well, I prefer my version. It helps to understand the code: the first if and the second if are not for the same thing, and merging them makes it harder for me to see what the code does.

**Comment by Peltoche** [comment]
> Well, I prefer my version. It helps to understand the code: the first if and the second if are not for the same thing, and merging them makes it harder for me to see what the code does.

Understandable. After a reread I agree that the `if/else if` pattern doesn't match. I would like to propose you a second solution with an early return.

**Comment by nono** [comment]
It's better. I still have a light preference for the original code, but if the goal is to enable gocritic, I can accept this PR.

**Comment by Peltoche** [comment]
> if the goal is to enable gocritic, I can accept this PR.

The commit is ready, it just require to merge this PR and #3610 because it require to have the config file in order to remove some sub-lint. I can push it now if you want to take a look.

**Review by nono — APPROVED** [review]

**Pull request merged**
