### PR TITLE
Upload the coverage to codecove after the tests

### LINKED ISSUE #3798: Discussion: Code coverage integration?
Hi @nono 

It would be great to have some coverage information. This could help us to know if a part of the codebase need more tests. 

What do you think of adding a coverage integration like https://about.codecov.io/?

### PR DESCRIPTION
**Pull request by Peltoche**
This review is based on the following documentation: https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/

It also add a check for dataraces

Fix #3798

### CODE REVIEW

**Comment by nono** [comment]
It looks like we have some data races detected

**Comment by Peltoche** [comment]
Arg! Indeed... A `-` was missing...

**Comment by Peltoche** [comment]
Yep, I have remove the `-race` flag and put back the `-p 1` flag in order to keep the job as similar as possible. I will try to add the `-race` flag in an another PR.

**Comment by Peltoche** [comment]
And now we fall back on the same errors than #3796. We will need to merge it before this one

**Comment by nono** [comment]
By the way, I've just seen a new post about code coverage: https://go.dev/blog/integration-test-coverage (not yet read).

**Comment by Peltoche** [comment]
> By the way, I've just seen a new post about code coverage: https://go.dev/blog/integration-test-coverage (not yet read).

Yep, seen it. Not sure that's useful for us. Maybe for the Ruby tests but I don't know how the coverage tool is able to merge two separate coverage reports.

**Review by nono — APPROVED** [review]

**Pull request merged**
