### PR TITLE
feat: Add app.editor reading from manifest

### PR DESCRIPTION
**Pull request by GoOz**
So we can use it to display the name of the app in the Cozy-bar

### CODE REVIEW

**Comment by GoOz** [comment]
[(1) [BAR-11 / E-36] ETDeveloppeur d'application tiers, je n'ai pas 'Cozy' devant le nom de mon app](https://trello.com/c/zsq1dQq4/298-1-bar-11-e-36-etdeveloppeur-d-application-tiers-je-n-ai-pas-cozy-devant-le-nom-de-mon-app)

**Comment by GoOz** [comment]
@nono Well, because the author wouldn't be displayed. For example, if John is the author of the app Todo, he doesn't want his app to be named "John Todo", just "Todo", but he surely wants his name known as the author. 
With the Editor choice, i kinda went for a thing like Microsoft Office or Apple Mail or Mozilla Firefox, you see?

But you're right, i'll update the documentation, my bad. :)

**Comment by nono** [comment]
There is also the documentation about the manifest to update: https://github.com/cozy/cozy-stack/blob/master/docs/apps.md#the-manifest

**Comment by GoOz** [comment]
Miss this one. thank you.

**Pull request merged**
