### PR TITLE
Apply more strict jobs permissions

### PR DESCRIPTION
**Pull request by jinroh**
Waiting for update in some applications (mainly collect) to apply this patch.
cc @CPatchane @gregorylegarec

This reverts commit 616f9fa0764a50a6fe2bcf297da938a67b2e5a87.

### CODE REVIEW

**Comment by nono** [comment]
Ping @CPatchane @gregorylegarec -> when will we be able to apply this change?

**Comment by CPatchane** [comment]
Is this about have restrictions according to a specific working?

**Comment by nono** [comment]
@CPatchane yes, the goal is the forbid the permission for all the workers and only let apps have permissions on specific worker(s).

**Comment by gregorylegarec** [comment]
What the status of this PR ? I totally forgot what it was all about.

**Comment by jinroh** [comment]
@gregorylegarec depends on the applications using permissions on `io.cozy.jobs`, and especially collect.
If applications still have permissions on the whole `io.cozy.jobs` doctype, this PR cannot be merged. 

However, if applications have their permissions limited to the `worker_type` they actually care about, we should be ready to merge this.

**Comment by gregorylegarec** [comment]
@jinroh Thanks for those precisions ! 👌

**Comment by nono** [comment]
This PR is opened for a long time and has several files in conflict. Some applications like cozy-home still have permissions on the whole `io.cozy.jobs` and `io.cozy.triggers` doctypes (I think it is required for `io.cozy.jobs` for the realtime in the current state of the stack). Let's close the PR, we will see later what to do about that.

**Pull request closed without merging**
