### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by lespacedunmatin**

### CODE REVIEW

**Comment by nono** [comment]
Hmmm, I thought that the slug must be given in the URL to install a konnector.

@aenario do you confirm?

**Comment by jinroh** [comment]
Hmm, this was not a typo. Can you explain @lespacedunmatin ?

**Comment by jinroh** [comment]
I think this PR is not correct. Please @lespacedunmatin, re-open if you feel otherwise.

**Comment by lespacedunmatin** [comment]
It was because at the beginning of the doc, in `Routes` -> `konnectors`, we only have a route `POST /konnectors?Source=xxxx`, and no `POST /konnectors/:KonnectorSlug?Source=xxx`route described. Si maybe the issue is in the Routes section.

**Comment by nono** [comment]
Fixed by https://github.com/cozy/cozy-stack/commit/5dace45713969d919284d8c2b9de5a2ce862a340

**Pull request closed without merging**
